# Generated by Django 3.2.16 on 2023-01-03 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeavesColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[], default=uuid.uuid1, max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Цвет листьев',
                'verbose_name_plural': 'Цвета листвьев',
            },
        ),
        migrations.CreateModel(
            name='LeavesColourChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[], default=uuid.uuid1, max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Изменение окраски листьев',
                'verbose_name_plural': 'Изменения окраски листьев',
            },
        ),
        migrations.CreateModel(
            name='LifeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[], default=uuid.uuid1, max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Жизненная форма растения',
                'verbose_name_plural': 'Жизненные формы растений',
            },
        ),
        migrations.CreateModel(
            name='TypePlantDeciduous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[], default=uuid.uuid1, max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Тип растения',
                'verbose_name_plural': 'Типы растений',
            },
        ),
        migrations.CreateModel(
            name='YoungLeavesColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[], default=uuid.uuid1, max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Цвет молодых листьев',
                'verbose_name_plural': 'Цвета молодых листвьев',
            },
        ),
    ]
