# Generated by Django 3.2.16 on 2023-01-03 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phytomorphology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeform',
            name='name',
            field=models.CharField(choices=[('Дерево', 'Дерево')], default=uuid.uuid1, max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
