# Generated by Django 3.2.16 on 2023-01-03 14:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phytomorphology', '0003_alter_lifeform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavescolourchanges',
            name='name',
            field=models.CharField(choices=[('Осенняя окраска', 'Осенняя окраска'), ('Молодые листья', 'Молодые листья'), ('Отсутствует', 'Отсутствует')], default=uuid.uuid1, max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='lifeform',
            name='name',
            field=models.CharField(choices=[], default=uuid.uuid1, max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='typeplantdeciduous',
            name='name',
            field=models.CharField(choices=[('Листопадное', 'Листопадное'), ('Полувечнозеленое', 'Полувечнозеленое'), ('Вечнозеленое', 'Вечнозеленое')], default=uuid.uuid1, max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
