# Generated by Django 3.2.16 on 2023-01-03 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phytomorphology', '0004_auto_20230103_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavescolour',
            name='name',
            field=models.CharField(choices=[('Белый', 'Белый'), ('Бронзоватый', 'Бронзоватый'), ('Голубой', 'Голубой'), ('Желтый', 'Желтый'), ('Зеленый', 'Зеленый'), ('Красный', 'Красный'), ('Оранжевый', 'Оранжевый'), ('Розовый', 'Розовый'), ('Серебристый', 'Серебристый'), ('Серый', 'Серый'), ('Сизый', 'Сизый'), ('Фиолетовый', 'Фиолетовый')], default=uuid.uuid1, max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='lifeform',
            name='name',
            field=models.CharField(choices=[('Дерево', 'Дерево'), ('Кустарник', 'Кустарник'), ('Почвопокровный кустарник', 'Почвопокровный кустарник'), ('Лиана', 'Лиана')], default=uuid.uuid1, max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='youngleavescolour',
            name='name',
            field=models.CharField(choices=[('Белый', 'Белый'), ('Бронзоватый', 'Бронзоватый'), ('Голубой', 'Голубой'), ('Желтый', 'Желтый'), ('Зеленый', 'Зеленый'), ('Красный', 'Красный'), ('Оранжевый', 'Оранжевый'), ('Розовый', 'Розовый'), ('Серебристый', 'Серебристый'), ('Серый', 'Серый'), ('Сизый', 'Сизый'), ('Фиолетовый', 'Фиолетовый')], default=uuid.uuid1, max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
