# Generated by Django 3.2.16 on 2023-01-03 20:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phytomorphology', '0009_auto_20230103_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarkColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Белый', 'Белый'), ('Бронзоватый', 'Бронзоватый'), ('Голубой', 'Голубой'), ('Желтый', 'Желтый'), ('Зеленый', 'Зеленый'), ('Коричневый', 'Коричневый'), ('Красный', 'Красный'), ('Оранжевый', 'Оранжевый'), ('Розовый', 'Розовый'), ('Серебристый', 'Серебристый'), ('Серый', 'Серый'), ('Сизый', 'Сизый'), ('Синий', 'Синий'), ('Фиолетовый', 'Фиолетовый'), ('Черный', 'Черный'), ('Не являются декоративными', 'Не являются декоративными'), ('Отсутствуют', 'Отсутствуют')], default=uuid.uuid1, max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Цвет коры',
                'verbose_name_plural': 'Цвета коры',
            },
        ),
        migrations.CreateModel(
            name='FruitColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Белый', 'Белый'), ('Бронзоватый', 'Бронзоватый'), ('Голубой', 'Голубой'), ('Желтый', 'Желтый'), ('Зеленый', 'Зеленый'), ('Коричневый', 'Коричневый'), ('Красный', 'Красный'), ('Оранжевый', 'Оранжевый'), ('Розовый', 'Розовый'), ('Серебристый', 'Серебристый'), ('Серый', 'Серый'), ('Сизый', 'Сизый'), ('Синий', 'Синий'), ('Фиолетовый', 'Фиолетовый'), ('Черный', 'Черный'), ('Не являются декоративными', 'Не являются декоративными'), ('Отсутствуют', 'Отсутствуют')], default=uuid.uuid1, max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Цвет плодов',
                'verbose_name_plural': 'Цвета плодов',
            },
        ),
        migrations.CreateModel(
            name='OtherTypesDecoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Декоративность в зимний период', 'Декоративность в зимний период'), ('Цветки до появления листьев', 'Цветки до появления листьев'), ('Цветки после опадания листьев', 'Цветки после опадания листьев'), ('Форма ветвей', 'Форма ветвей'), ('Отсутствуют', 'Отсутствуют')], default=uuid.uuid1, max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Прочие виды декоратичности',
                'verbose_name_plural': 'Прочие виды декоратичности',
            },
        ),
        migrations.CreateModel(
            name='PoisonParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Кора', 'Кора'), ('Корни', 'Корни'), ('Листья', 'Листья'), ('Плоды', 'Плоды'), ('Семена', 'Семена'), ('Сок', 'Сок'), ('Цветы', 'Цветы'), ('Отсутствуют', 'Отсутствуют')], default=uuid.uuid1, max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Ядовитые части',
                'verbose_name_plural': 'Ядовитые части',
            },
        ),
    ]
