version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - data_value:/var/lib/postgresql/data/
    env_file:
      - ../.env

  web:
    build: ..
    image: plantsfinder-web
    restart: always
    ports:
     - "8000:8000"
    volumes:
      - static_value:/app/frontend/static/
      - media_value:/app/frontend/media/
    depends_on:
      - db
    env_file:
      - ../.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ../../../etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email inozemtsevserge@gmail.com --agree-tos --no-eff-email --staging -d plantsfinder.net

volumes:
  data_value:
  static_value:
  media_value:
