# Generated by Django 3.2.16 on 2023-01-03 14:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilfertility',
            name='name',
            field=models.CharField(choices=[('Плодородные', 'Плодородные'), ('Умеренно плодородные', 'Умеренно плодородные'), ('Бедные', 'Бедные')], default=uuid.uuid1, max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='soilmoisture',
            name='name',
            field=models.CharField(choices=[('Возможна засуха', 'Возможна засуха'), ('Низкая', 'Низкая'), ('Умеренная', 'Умеренная'), ('Высокая', 'Высокая'), ('Возможны затопления', 'Возможны затопления')], default=uuid.uuid1, max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='soiltype',
            name='name',
            field=models.CharField(choices=[('Легкие', 'Легкие'), ('Среднетяжелые', 'Среднетяжелые'), ('Тяжелые', 'Тяжелые')], default=uuid.uuid1, max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sun',
            name='name',
            field=models.CharField(choices=[('Солнце', 'Солнце'), ('Полутень', 'Полутень'), ('Тень', 'Тень')], default=uuid.uuid1, max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
